/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppTrainingPlansIndexRouteImport } from './routes/_app/training-plans/index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppBoardsIndexRouteImport } from './routes/_app/boards/index'
import { Route as AppTrainingPlansPlanIdRouteImport } from './routes/_app/training-plans/$planId'
import { Route as AppSessionsNewRouteImport } from './routes/_app/sessions/new'
import { Route as AppProfileEditRouteImport } from './routes/_app/profile/edit'
import { Route as AppProfileChangePasswordRouteImport } from './routes/_app/profile/change-password'
import { Route as AppBoardsNewRouteImport } from './routes/_app/boards/new'
import { Route as AppSessionsSessionIdIndexRouteImport } from './routes/_app/sessions/$sessionId/index'
import { Route as AppSessionsSessionIdUploadRouteImport } from './routes/_app/sessions/$sessionId/upload'
import { Route as AppSessionsSessionIdReviewRouteImport } from './routes/_app/sessions/$sessionId/review'
import { Route as AppSessionsSessionIdPlanRouteImport } from './routes/_app/sessions/$sessionId/plan'
import { Route as AppBoardsBoardIdEditRouteImport } from './routes/_app/boards/$boardId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingPlansIndexRoute = AppTrainingPlansIndexRouteImport.update({
  id: '/training-plans/',
  path: '/training-plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardsIndexRoute = AppBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingPlansPlanIdRoute = AppTrainingPlansPlanIdRouteImport.update({
  id: '/training-plans/$planId',
  path: '/training-plans/$planId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileChangePasswordRoute =
  AppProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AppRoute,
  } as any)
const AppBoardsNewRoute = AppBoardsNewRouteImport.update({
  id: '/boards/new',
  path: '/boards/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdIndexRoute =
  AppSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSessionsSessionIdUploadRoute =
  AppSessionsSessionIdUploadRouteImport.update({
    id: '/sessions/$sessionId/upload',
    path: '/sessions/$sessionId/upload',
    getParentRoute: () => AppRoute,
  } as any)
const AppSessionsSessionIdReviewRoute =
  AppSessionsSessionIdReviewRouteImport.update({
    id: '/sessions/$sessionId/review',
    path: '/sessions/$sessionId/review',
    getParentRoute: () => AppRoute,
  } as any)
const AppSessionsSessionIdPlanRoute =
  AppSessionsSessionIdPlanRouteImport.update({
    id: '/sessions/$sessionId/plan',
    path: '/sessions/$sessionId/plan',
    getParentRoute: () => AppRoute,
  } as any)
const AppBoardsBoardIdEditRoute = AppBoardsBoardIdEditRouteImport.update({
  id: '/boards/$boardId/edit',
  path: '/boards/$boardId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/boards/new': typeof AppBoardsNewRoute
  '/profile/change-password': typeof AppProfileChangePasswordRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/sessions/new': typeof AppSessionsNewRoute
  '/training-plans/$planId': typeof AppTrainingPlansPlanIdRoute
  '/boards/': typeof AppBoardsIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/training-plans/': typeof AppTrainingPlansIndexRoute
  '/boards/$boardId/edit': typeof AppBoardsBoardIdEditRoute
  '/sessions/$sessionId/plan': typeof AppSessionsSessionIdPlanRoute
  '/sessions/$sessionId/review': typeof AppSessionsSessionIdReviewRoute
  '/sessions/$sessionId/upload': typeof AppSessionsSessionIdUploadRoute
  '/sessions/$sessionId/': typeof AppSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/boards/new': typeof AppBoardsNewRoute
  '/profile/change-password': typeof AppProfileChangePasswordRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/sessions/new': typeof AppSessionsNewRoute
  '/training-plans/$planId': typeof AppTrainingPlansPlanIdRoute
  '/boards': typeof AppBoardsIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/training-plans': typeof AppTrainingPlansIndexRoute
  '/boards/$boardId/edit': typeof AppBoardsBoardIdEditRoute
  '/sessions/$sessionId/plan': typeof AppSessionsSessionIdPlanRoute
  '/sessions/$sessionId/review': typeof AppSessionsSessionIdReviewRoute
  '/sessions/$sessionId/upload': typeof AppSessionsSessionIdUploadRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/boards/new': typeof AppBoardsNewRoute
  '/_app/profile/change-password': typeof AppProfileChangePasswordRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/sessions/new': typeof AppSessionsNewRoute
  '/_app/training-plans/$planId': typeof AppTrainingPlansPlanIdRoute
  '/_app/boards/': typeof AppBoardsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/training-plans/': typeof AppTrainingPlansIndexRoute
  '/_app/boards/$boardId/edit': typeof AppBoardsBoardIdEditRoute
  '/_app/sessions/$sessionId/plan': typeof AppSessionsSessionIdPlanRoute
  '/_app/sessions/$sessionId/review': typeof AppSessionsSessionIdReviewRoute
  '/_app/sessions/$sessionId/upload': typeof AppSessionsSessionIdUploadRoute
  '/_app/sessions/$sessionId/': typeof AppSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/boards/new'
    | '/profile/change-password'
    | '/profile/edit'
    | '/sessions/new'
    | '/training-plans/$planId'
    | '/boards/'
    | '/profile/'
    | '/sessions/'
    | '/training-plans/'
    | '/boards/$boardId/edit'
    | '/sessions/$sessionId/plan'
    | '/sessions/$sessionId/review'
    | '/sessions/$sessionId/upload'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/boards/new'
    | '/profile/change-password'
    | '/profile/edit'
    | '/sessions/new'
    | '/training-plans/$planId'
    | '/boards'
    | '/profile'
    | '/sessions'
    | '/training-plans'
    | '/boards/$boardId/edit'
    | '/sessions/$sessionId/plan'
    | '/sessions/$sessionId/review'
    | '/sessions/$sessionId/upload'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_app/boards/new'
    | '/_app/profile/change-password'
    | '/_app/profile/edit'
    | '/_app/sessions/new'
    | '/_app/training-plans/$planId'
    | '/_app/boards/'
    | '/_app/profile/'
    | '/_app/sessions/'
    | '/_app/training-plans/'
    | '/_app/boards/$boardId/edit'
    | '/_app/sessions/$sessionId/plan'
    | '/_app/sessions/$sessionId/review'
    | '/_app/sessions/$sessionId/upload'
    | '/_app/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/training-plans/': {
      id: '/_app/training-plans/'
      path: '/training-plans'
      fullPath: '/training-plans/'
      preLoaderRoute: typeof AppTrainingPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boards/': {
      id: '/_app/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof AppBoardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/training-plans/$planId': {
      id: '/_app/training-plans/$planId'
      path: '/training-plans/$planId'
      fullPath: '/training-plans/$planId'
      preLoaderRoute: typeof AppTrainingPlansPlanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/new': {
      id: '/_app/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/change-password': {
      id: '/_app/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AppProfileChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boards/new': {
      id: '/_app/boards/new'
      path: '/boards/new'
      fullPath: '/boards/new'
      preLoaderRoute: typeof AppBoardsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId/': {
      id: '/_app/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof AppSessionsSessionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId/upload': {
      id: '/_app/sessions/$sessionId/upload'
      path: '/sessions/$sessionId/upload'
      fullPath: '/sessions/$sessionId/upload'
      preLoaderRoute: typeof AppSessionsSessionIdUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId/review': {
      id: '/_app/sessions/$sessionId/review'
      path: '/sessions/$sessionId/review'
      fullPath: '/sessions/$sessionId/review'
      preLoaderRoute: typeof AppSessionsSessionIdReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId/plan': {
      id: '/_app/sessions/$sessionId/plan'
      path: '/sessions/$sessionId/plan'
      fullPath: '/sessions/$sessionId/plan'
      preLoaderRoute: typeof AppSessionsSessionIdPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boards/$boardId/edit': {
      id: '/_app/boards/$boardId/edit'
      path: '/boards/$boardId/edit'
      fullPath: '/boards/$boardId/edit'
      preLoaderRoute: typeof AppBoardsBoardIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppBoardsNewRoute: typeof AppBoardsNewRoute
  AppProfileChangePasswordRoute: typeof AppProfileChangePasswordRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppSessionsNewRoute: typeof AppSessionsNewRoute
  AppTrainingPlansPlanIdRoute: typeof AppTrainingPlansPlanIdRoute
  AppBoardsIndexRoute: typeof AppBoardsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppTrainingPlansIndexRoute: typeof AppTrainingPlansIndexRoute
  AppBoardsBoardIdEditRoute: typeof AppBoardsBoardIdEditRoute
  AppSessionsSessionIdPlanRoute: typeof AppSessionsSessionIdPlanRoute
  AppSessionsSessionIdReviewRoute: typeof AppSessionsSessionIdReviewRoute
  AppSessionsSessionIdUploadRoute: typeof AppSessionsSessionIdUploadRoute
  AppSessionsSessionIdIndexRoute: typeof AppSessionsSessionIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppBoardsNewRoute: AppBoardsNewRoute,
  AppProfileChangePasswordRoute: AppProfileChangePasswordRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppSessionsNewRoute: AppSessionsNewRoute,
  AppTrainingPlansPlanIdRoute: AppTrainingPlansPlanIdRoute,
  AppBoardsIndexRoute: AppBoardsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppTrainingPlansIndexRoute: AppTrainingPlansIndexRoute,
  AppBoardsBoardIdEditRoute: AppBoardsBoardIdEditRoute,
  AppSessionsSessionIdPlanRoute: AppSessionsSessionIdPlanRoute,
  AppSessionsSessionIdReviewRoute: AppSessionsSessionIdReviewRoute,
  AppSessionsSessionIdUploadRoute: AppSessionsSessionIdUploadRoute,
  AppSessionsSessionIdIndexRoute: AppSessionsSessionIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
